// build-time-2025-10-15T13:16:48.632Z
// Copyright 2006-2025 ClickTale Ltd., US Patent Pending

window.ClickTaleGlobal = window.ClickTaleGlobal || {};
window.ClickTaleSettings = window.ClickTaleSettings || {};

ClickTaleGlobal.init = ClickTaleGlobal.init || {};
ClickTaleGlobal.scripts = ClickTaleGlobal.scripts || {};

ClickTaleGlobal.scripts.filter = ClickTaleGlobal.scripts.filter || (function () {
	var recordingThreshold = Math.random() * 100;

	return {
		isRecordingApproved: function(percentage) {
			return recordingThreshold <= percentage;
		}
	}
})();


// Copyright 2006-2025 ClickTale Ltd., US Patent Pending
// PID: 1009



/*browsers exclusion start*/ ClickTaleSettings.PTC.doOnlyWhen = function (toDoHandler, toCheckHandler, interval, times, failHandler) {
    if ((!toDoHandler) || (!toCheckHandler)) return;
    if (typeof interval == 'undefined') interval = 1000;
    if (typeof times == 'undefined') times = 20;

    if (--times < 0) {
        if (typeof failHandler === 'function') {
            failHandler();
        }
        return;
    }
    if (toCheckHandler()) {
        toDoHandler();
        return;
    }

    setTimeout(function () { ClickTaleSettings.PTC.doOnlyWhen(toDoHandler, toCheckHandler, interval, times, failHandler); }, interval);
}
ClickTaleSettings.PTC.doOnlyWhen(function () {
    if (window.ClickTaleSettings.PTC.okToRunPCC) {
        (function(){
            window.ClickTaleSettings = window.ClickTaleSettings || {};
            ClickTaleSettings.PTC = ClickTaleSettings.PTC || {};
            ClickTaleSettings.PTC.originalPCCLocation = 'P32_PID1009';
            
            
            function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function h(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
h("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});
var ea="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)Object.prototype.hasOwnProperty.call(d,e)&&(a[e]=d[e])}return a};h("Object.assign",function(a){return a||ea});var fa;function n(a,b,c,d,e){a&&b&&("undefined"==typeof c&&(c=1E3),"undefined"==typeof d&&(d=20),0>--d?"function"===typeof e&&e():b()?a():setTimeout(function(){n(a,b,c,d,e)},c))}
function ha(a){var b="someText".trim,c=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;fa=b&&!b.call(new String("\ufeff\u00a0"))?function(d){return null==d?"":b.call(d)}:function(d){return null==d?"":(d+"").replace(c,"")};return fa(a)}
function ia(a){return"string"==typeof a?ia(document.querySelectorAll(a)):Array.prototype.filter.call(a,function(b){if(b){var c=b.getRootNode?b.getRootNode({composed:!1}):b.ownerDocument;b=!!(b.compareDocumentPosition(c)&Node.DOCUMENT_POSITION_CONTAINS&&(b.offsetWidth||b.offsetHeight||b.getClientRects().length))}else b=!1;return b})};function q(a,b){b||(b=document);return b instanceof Element||b instanceof Document?Array.prototype.slice.call(b.querySelectorAll(a)):"string"===typeof b?q(a,document.querySelectorAll(b)):Array.isArray(b)||b instanceof HTMLCollection||b instanceof NodeList?Array.prototype.reduce.call(b,function(c,d){return c.concat(Array.prototype.slice.call(d.querySelectorAll(a)))},[]):[]}
function t(a,b){if(a&&a.nodeType&&9===a.nodeType)return!1;var c=Element.prototype;t=function(d,e){return d&&document.documentElement.contains(d)?t.matches.call(d,e):!1};t.matches=c.webkitMatchesSelector||c.mozMatchesSelector||c.msMatchesSelector||c.matches;return t(a,b)}function v(a,b){v=Element.prototype.closest?function(c,d){return c&&c instanceof Element?Element.prototype.closest.call(c,d):null}:function(c,d){for(;c&&!t(c,d);)c=c.parentElement;return c};return v(a,b)};var ja=!1,la=Object.defineProperty&&Object.defineProperty({},"passive",{get:function(){ja=!0}});document.addEventListener("test",function(){},la);var w=ja?{passive:!0,capture:!0}:!0,ma=0;function x(a){function b(){2==++c&&a()}if(!~x.l.indexOf(a)){x.l.push(a);var c=0;na(b);if("function"==typeof ClickTaleIsRecording&&!0===ClickTaleIsRecording())b();else{var d=window.ClickTaleOnRecording||function(){};window.ClickTaleOnRecording=function(){b();return d.apply(this,arguments)}}}}x.l=[];
function na(a){function b(){c||(c=!0,a())}var c=!1;"loading"!=document.readyState?b():document.addEventListener&&document.addEventListener("DOMContentLoaded",b,!1)}
function y(a,b,c,d,e){if("string"===typeof b&&-1!=b.indexOf(" "))return b.split(/\s+/).forEach(function(l){return y(a,l,c,d,e)}),a;if("string"===typeof a)Array.prototype.forEach.call(document.querySelectorAll(a),function(l){y(l,b,c,d,e)});else if(a instanceof Array||a instanceof NodeList)Array.prototype.forEach.call(a,function(l){y(l,b,c,d,e)});else{var k="";"string"==typeof c&&("mouseenter"==b?(b="mouseover",k="mouseenter"):"mouseleave"==b&&(b="mouseout",k="mouseleave"));a.addEventListener(b,function(l,
f,p,g,m,u){return function(D){if("function"===typeof p)p.apply(this,arguments),m&&l.removeEventListener(f,arguments.callee,w);else{var C=D.relatedTarget,r=v(D.target,p);r&&l.compareDocumentPosition(r)&Node.DOCUMENT_POSITION_CONTAINED_BY&&("mouseenter"==u||"mouseleave"==u?C&&(C==r||r.compareDocumentPosition(C)&Node.DOCUMENT_POSITION_CONTAINED_BY)||g.apply(r,arguments):g.apply(r,arguments),m&&l.removeEventListener(f,arguments.callee,w))}}}(a,b,c,d,e,k),w)}return a}
function oa(a,b){document.addEventListener("mouseup",function(c){a===c.target&&b();document.removeEventListener("mouseup",arguments.callee,w)},w)}function pa(a,b){function c(d){document.removeEventListener("touchend",arguments.callee,w);a===d.target&&b()}document.addEventListener("touchend",c,w);document.addEventListener("touchmove",function(d){document.removeEventListener("touchmove",arguments.callee,w);document.removeEventListener("touchend",c,w)},w)}
function A(a,b){var c=B();c&&(c.m?A=pa:A=oa,A(a,b))};function qa(a){return btoa(encodeURIComponent(a).replace(/%([0-9A-F]{2})/g,function(b,c){return String.fromCharCode(+("0x"+c))}))};function E(a){window._uxa=window._uxa||[];window._uxa.push.apply(window._uxa,arguments)}function ra(a){a=void 0===a?window.location.pathname+window.location.hash.replace("#","?__"):a;E(["trackPageview",a])}function sa(a){E(["setCustomVariable",2,"paymentOption",a])};function ta(a){function b(){"function"===typeof D&&D();var z=g?g():location;ua?F(function(){"function"===typeof a&&a()},z.href,C,e):va&&(ra(z.pathname),!0===m&&"function"===typeof a&&a());C=z.href}function c(z){if(r&&(r=!1,setTimeout(function(){r=!0},p),"function"!==typeof f||f()))if(isNaN(l)||"number"!=typeof l||z){if("function"===typeof ClickTaleIsRecording&&ClickTaleIsRecording())ua=!0,G();else{var S;"function"!==typeof ClickTaleStop&&(S=window.ClickTaleOnStop)&&Array.isArray(S)&&S.forEach(function(ka){"function"===
typeof ka&&ka.call(window)});va=!0}k()||(d?"string"===typeof d?n(b,function(){return!!document.querySelector(d+"")},1E3,10,b):"function"===typeof d?n(b,d,1E3,10,b):setTimeout(b,2E3):setTimeout(b,2E3))}else z=l||0,setTimeout(c.bind(null,!0),z)}if("function"!=typeof a&&a){var d=a.K;var e=a.I;var k=a.C;var l=a.B;var f=a.H;var p=a.J;var g=a.F;var m=a.G;var u=a.D;var D=a.A;a=a.s}u=u||!1;k=k||function(){return!1};a=a||function(){};p=p||400;var C=(g?g():location).href;e||isNaN(d)||(e=d,d="");e=e||2E3;var r=
!0;window.history&&(H=history.replaceState,history.replaceState=function(){u?c():setTimeout(c,5);return H.apply(history,arguments)},I=history.pushState,history.pushState=function(){u?c():setTimeout(c,5);return I.apply(history,arguments)},J=function(){u?c():setTimeout(c,5)},window.addEventListener("popstate",J,!1))}var va,H,I,J,ua=!1;function G(){"function"===typeof ClickTaleStop&&ClickTaleStop()}function K(a,b){"function"===typeof ClickTaleEvent&&(b?!0!==K.flags[a]&&(K.flags[a]=!0,ClickTaleEvent(a)):ClickTaleEvent(a))}K.flags={};function wa(a,b){"function"===typeof ClickTaleLogical&&(K.flags={},L.h&&L.h instanceof xa&&L.h.clear(),b?ClickTaleLogical(a,b):ClickTaleLogical(a))}function B(){if("function"===typeof ClickTaleDetectAgent){var a=ClickTaleDetectAgent();if(a)return B=function(){return a},B()}return null}
function F(a,b,c,d){F.j&&(F.j=!1,d=d||400,"number"==typeof c&&(d=c,c=""),b=b||document.location.href,G(),window.ClickTaleIncludedOnDOMReady=!0,window.ClickTaleIncludedOnWindowLoad=!0,wa(b,c),n(a,ClickTaleIsRecording,1E3,2),setTimeout(function(){F.j=!0},d))}F.j=!0;
function ya(a){var b=M,c=za,d=N;if(O){O=!1;var e=e||400;d?(G(),window.ClickTaleIncludedOnDOMReady=!0,window.ClickTaleIncludedOnWindowLoad=!0,wa(a.href,c)):(Array.isArray(window.ClickTaleOnStop)&&window.ClickTaleOnStop.forEach(function(k){if("function"===typeof k)try{k.call(window)}catch(l){}}),ra(a.pathname));b();clearTimeout(Aa);Aa=setTimeout(function(){O=!0},e)}}var Aa=-1,O=!0;
function xa(){this.i=!1;this.g="";this.init=function(a){this.i||(this.i=!0,document.addEventListener("input",this.o,w));this.u(a);this.g=this.g?this.g+","+a:a};this.o=function(a){a=a.target;t(a,this.g)&&(q(this.g),qa(a.value))}.bind(this);this.u=function(a){var b="";q(a).forEach(function(c,d){b+="document.querySelectorAll('"+a+"')["+d+"].value = Base64Decode('"+qa(c.value)+"'); "})};this.clear=function(){document.removeEventListener("input",this.o,w);this.i=!1;this.g=""}}
function L(a){L.h=L.h||new xa;L.h.init(a)}L.h=null;var P=K,Ba=y;function Q(a,b){return a instanceof Element?b instanceof Element?a===b:t(a,b):!1}var Ca=v,Da=ia,Ea=A;var R="",T="",N=!1,Fa=!1,Ga=!0,za=location.href,U="",Ha="",Ia="",V,W;function Ja(){var a=document.querySelector('ol.step-indicator li[aria-current="step"]'),b=document.querySelectorAll("ol.step-indicator li");if(a&&b)return["Build","365","Accessories"][Array.prototype.indexOf.call(b,a)]}
function X(){var a=document.querySelector("h1.c-scheduler-header");if(a)switch(a.textContent.trim()){case "Book an appointment":a=[];var b=a.concat,c=document.querySelectorAll('.c-accordion-header[aria-expanded="true"] h5');if(!(c instanceof Array)){var d="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];c=d?d.call(c):{next:aa(c)};for(var e=[];!(d=c.next()).done;)e.push(d.value);c=e}if(a=b.call(a,c).slice(-1)[0])return a.textContent.trim().replace(/(Step.*)(:.*)/,"$1");break;case "Review and confirm your appointment":return"Reviewandconfirm";
case "You're all set!":return"allset"}}function Ka(){var a=La("id2="),b=La("totamtwotx="),c=U.replace(/%../g,"").replace(/(.*)(cur)(:?)([a-z]{3})(.*)/,"$4");a&&b&&c&&(E(["ec:transaction:create",{id:a,revenue:b,currency:c}]),E(["ec:transaction:send"]))}function La(a){a=U.split(a);return a[1]?a[1].split("&")[0]:!1}
function Ma(){if(window.MutationObserver){var a={area1:"type",area2:"date",area3:"info"},b;n(function(){var c=new window.MutationObserver(function(){var e=Da('div[id^="area"]')[0];(e=!!e&&a[e.id])&&e!==Ia&&(Ia=e,c.disconnect(),Y(e))}),d={attributes:!0,attributeFilter:["style"]};c&&"function"===typeof c.observe&&c.observe(b,d)},function(){b=Da('div[id^="area"]')[0];return!!b},400,20)}}
function Y(a){a=a?"?__"+a.toString().replaceAll(" ","_"):"";var b=Object.assign({},document.location);b.href+=a;b.pathname+=a;window._uxa=window._uxa||[];window._uxa.push(["setQuery",""]);ya(b)}function Z(a){a&&"string"===typeof a&&P(a)}function Na(a){var b="";a&&"string"==typeof a&&(a=document.querySelector(a));a&&a instanceof HTMLElement&&(b=a.textContent||a.innerText||a.value||"")&&(b=ha(b.replace(/\s+/g," ")));return b}
function Oa(){n(function(){P("onload | Configure your Surface | 4 steps")},function(){return 3<document.querySelectorAll('[id*="accordion"]').length},500,6)}
function M(){R="";za=location.href;T=document.location.pathname.toLowerCase();Ha=document.location.host.toLowerCase();U=document.location.search.toLowerCase();sa("");if(Ga)Ga=!1;else for(var a=window.ClickTaleSettings&&window.ClickTaleSettings.PTC&&window.ClickTaleSettings.PTC.InitFuncs?window.ClickTaleSettings.PTC.InitFuncs:[],b=0,c=a.length;b<c;b++)if("function"===typeof a[b])a[b]();N||x(function(){N=!0});/store\/configure\/Surface/i.test(T)&&(W=Ja());"query.prod.cms.rt.microsoft.com"==Ha&&-1<U.indexOf("pn=congrats")&&
Ka();/digitalreservations\.microsoft\.com.*\/appointment\/create/.test(location.href)&&n(function(){},function(){V=X();return!!V},100,50,function(){V="Step_2"});n(function(){window._pageBITags.pageTags.expId.split(",").forEach(function(d){(d=d.replace(/^EX:/i,""))&&E(["trackDynamicVariable",{key:"EXP "+d,value:"true"}])})},function(){return window._pageBITags&&window._pageBITags.pageTags&&window._pageBITags.pageTags.expId},1E3,5);if("/en-us/store/apps/windows"===T)R="Apps Windows Page";else if("/en-us/store/apps"===
T)R="Apps Page";else if(-1<T.indexOf("/en-us/store/"))if(R=T.substring(13),-1<T.indexOf("/b/office"))for(a=document.querySelectorAll('header[role="tablist"] > a, .tabs-container > a'),b=0;b<a.length;b++)c=a[b].textContent,a[b].classList.contains("f-active")&&Z("Onload | Choose your office | "+c);else-1<T.indexOf("/p/")&&(R="SUS p");else-1<T.indexOf("/surface/")&&(R="Surface Landing (GCB)");""!==R&&P("Onload | "+R,!0);Oa();-1<T.indexOf("appointment/create")&&"answerdesk.microsoft.com"==window.location.hostname.toLowerCase()&&
setTimeout(function(){Ma()},300)}
function Pa(){var a="Submit feedback",b="etr";b="string"===typeof b?b.toLowerCase():"id";var c=!!window.CS_CONF&&!!window.CS_CONF.tagDeploymentMode&&"LOAD_CLICKTALE_PTC"===window.CS_CONF.tagDeploymentMode;switch(b){case "ets":case "etp":case "etr":a=window.CS_CONF&&1===window.CS_CONF.useMalkaPipeline?("etp"==b?"@ETP@":"@ETS@")+a:"@ET@"+a;c?E(["trackEventTriggerRecording",a]):"function"===typeof ClickTaleEventTrigger?ClickTaleEventTrigger(a):K(a,!0);break;default:a=(window.CS_CONF&&1===window.CS_CONF.useMalkaPipeline?
"@user-identifier@":"@ID@")+a,c?E(["trackPageEvent",a]):K(a,!0)}b={SiteNav:"Site Navigation",SiteContent:"Site Content",LanguageQuality:"Language Quality",SiteDesign:"Site Design",ProductInformation:"Lack of product information",SearchingProduct:"Searching the product",Other:"Other"};a={"R1Feedback-sat-0":"Satisfied","R1Feedback-sat-1":"Somewhat Satisfied","R1Feedback-sat-2":"Somewhat Dissatisfied","R1Feedback-sat-3":"Dissatisfied"};c=document.querySelector("form[name='feedback'] select");var d=document.querySelector('form[name="feedback"] input[type="radio"]:checked'),
e,k;c&&((c=c.value)&&(e=b[c]),d&&(b=d.id)&&(k=a[b]),e&&k&&(Z("Feedback | "+k),Z("Feedback | "+k+" | "+e)))}
function Qa(){if(!window.ClickTaleFirstPCCGo){window.ClickTaleFirstPCCGo=!0;var a=B();a&&(Fa=a.m);M();a="a";-1<location.pathname.toLowerCase().indexOf("store/b/holiday-gift-guide")?a+=",.c-mosaic-placement,.c-call-to-action":-1<location.href.toLowerCase().indexOf("microsoft.com/en-us/p/")?a+=",.pi-page-bar .pi-product-metadata":/store\/configure/i.test(T)&&(a+=',div[id*="OneStore-AccordionContainerModule"] div.drawer button');/\/en-us\/store\/b\/sale/i.test(T)&&(a+=',div[id^="oneStore-quicklinksmodule-"] a, div#primaryR1 section.m-content-placement-item');
/digitalreservations\.microsoft\.com.*\/appointment\/create/.test(location.href)&&(a+=', label.ms-ChoiceField-field, button.c-selection, button.ms-Button, .c-accordion-header[aria-expanded="false"], .c-edit button');a+=",form[name='feedback'] button,.m-heading-4 [id^=\"pivot-tab-primary\"]";var b=null,c=0;/store\/configure\/Surface/i.test(T)&&(a+=", .configuratorV3__bottom-bar button.btn-primary, li.step-indicator-step a, .bottom-bar-v35 button.btn-primary");Ba(document,Fa?"touchstart":"mousedown",
a,function(d){var e=d.target;Ea(e,function(k,l,f){return function(){if(/store\/configure\/Surface/i.test(T)&&Q(f,".configuratorV3__bottom-bar button.btn-primary, li.step-indicator-step a, .bottom-bar-v35 button.btn-primary")){var p=W;n(function(){Y(p)},function(){p=Ja();return W!=p},100,50)}/digitalreservations\.microsoft\.com.*\/appointment\/create/.test(location.href)&&(Q(f,"label.ms-ChoiceField-field, button.c-selection, button.ms-Button")&&setTimeout(function(){var m;n(function(){Y(m)},function(){m=
X();return!!m&&m!=V},100,100)},500),Q(f,'.c-accordion-header[aria-expanded="false"], .c-edit button')&&("Reviewandconfirm"==X()?P("edit from review"):P("edit from summary")));if(/\/en-us\/store\/b\/sale/i.test(T)&&Ca(k,'div[id^="oneStore-quicklinksmodule-"] a'))P("Sale | "+T.match(/[a-z]{2}-[a-z]{2}/i)+" | Clicked Quicklink: "+f.innerText.trim());else if(/\/en-us\/store\/b\/sale/i.test(T)&&Ca(k,"div#primaryR1 section.m-content-placement-item")){var g=f.querySelector("h3.c-heading");g||(g=f.parentElement,
g=!!g&&g.parentElement,g=!!g&&g.querySelector("h3.c-heading"));(g=!!g&&g.innerText)&&P("Sale | "+T.match(/[a-z]{2}-[a-z]{2}/i)+" | Clicked Tile: "+g.trim())}Q(f,"form[name='feedback'] button")?Pa():(Q(f,".pi-page-bar .pi-product-metadata")&&P("US Store | PDP Stick Nav | Clicked on product title",!0),Q(f,"a")&&/shop now/i.test(Na(f))?P("Action | Category List Page: Clicked on Shop now",!0):-1<T.indexOf("/en-us/store/b/microsoft-small-business")&&Q(f,'.m-heading-4 [id^="pivot-tab-primary"]')&&(b=f,
c=(new Date).getTime()/1E3,setTimeout(function(){var m=(new Date).getTime()/1E3;Q(f,b)&&3<m-c&&((m=f.innerText)&&Y(m),b=null,c=0)},3E3)))}.bind(f)}(e,d,this))})}}(function(a){function b(){2==++ma&&a()}na(b);if("function"==typeof ClickTale)b();else{Array.isArray(window.ClickTaleOnReadyList)&&window.ClickTaleOnReadyList.push(b);var c=window.ClickTaleOnRecording||function(){};window.ClickTaleOnRecording=function(){b();return c.apply(this,arguments)}}})(function(){Qa()});
window.clickTaleStartEventSignal=function(a){ya(document.location);a&&"string"===typeof a&&P(a)};window.clickTaleEndEventSignal=function(){H&&(history.replaceState=H);I&&(history.pushState=I);J&&window.removeEventListener("popstate",J,!1);G()};
0==location.href.indexOf("https://www.microsoft.com/store/")&&-1==location.href.indexOf("buyboxlitev2")&&ta({s:M,A:function(){if("https://www.microsoft.com/store/add-payment-option"==location.href){var a="";document.querySelector("input#cvvToken")?a="Add Payment Option: Credit Card":document.querySelector("input#msisdn")?a="Add Payment Option: Phone":document.querySelector("input#pidlddc-button-paypalSignInButton")&&(a="Add Payment Option: PayPal");a&&sa(a)}}});

        })();
    }
}, function () { return !!(window.ClickTaleSettings && ClickTaleSettings.PTC && typeof ClickTaleSettings.PTC.okToRunPCC != 'undefined'); }, 500, 20);

// signature-45ad36cc564b38cfe080832e6ddf3f72be8fc561846f46e4ce1eb4e146dc28f9